### ISSUE TITLE
There are spelling issues on the gifts page

### ISSUE THREAD

**Issue by ChristinaJackson** [zero-to-mastery/Santafied#180]
Spelling and punctuation needs to be fixed on gifts page

**Comment by katharinabrx** [comment]
I can look into this page and repair a few things

**Comment by cgunston** [comment]
Hi @ChristinaJackson, I have made some spelling and grammar fixes for the gift page here - https://github.com/zero-to-mastery/Santafied/pull/228 - please could you review?
