### ISSUE TITLE
Fix Index Carousel

### ISSUE THREAD

**Issue by anirudh-kac** [zero-to-mastery/Santafied#20]
Carousel overlaps the intro image and text on small and medium screen size:

![Screen Shot 2019-10-01 at 07 50 26](https://user-images.githubusercontent.com/42580581/65930341-ff9cd500-e422-11e9-9da1-751a032e0d63.png)

**Comment by MattCSmith** [comment]
For me the images are just stacked underneath each other. 
![image](https://user-images.githubusercontent.com/6190356/65948024-57dad380-e431-11e9-9008-a332e63d8e1f.png)
