### ISSUE TITLE
[Enhancement] - Change Navbar Style inline with new design

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#207]
Santa decided the navbar looks too crowded and would just like to add all the links to a single drop down and add a email subscriber form. 

Adjust the navbar on all pages to reflected the updated design, found [here](https://github.com/zero-to-mastery/Santafied/blob/master/design/newdesign.png)

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by Pr0ftR3gret** [comment]
I'd like to work on this on

**Comment by MattCSmith** [comment]
@Pr0ftR3gret awesome, go head 😸

**Comment by MattCSmith** [comment]
Closing as this appears to have been resolved
