### ISSUE TITLE
Javascript navbard dropdown generator function

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#208]
Updating the links on each page is becoming a real headache, causing a lot of broken links. 

In this task you need to create some Javascript that will have all the page links, generate the links for the new navbar drop down (see issue #207) and then inject them into the headers dropdown on each page. 

This way when a link needs adding or updating it can be done from the JS file. 
Ensure that you comment each navbar so other contributors know how to go about adding/editing links. 

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by CouchCat** [comment]
I would like to take this!

**Comment by CouchCat** [comment]
@MattCSmith All done 👏 Please close
