### ISSUE TITLE
Correct gifts page layout 

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#210]
The background images and colored background should reach each side of the page:

![image](https://user-images.githubusercontent.com/6190356/66208635-7cdb7a80-e6ad-11e9-9df4-b88e762068ba.png)

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by fabrizvi** [comment]
Hey, I would like to work on this issue?

**Comment by MattCSmith** [comment]
@fabrizvi Awesome go for it

**Comment by fabrizvi** [comment]
I resolved it already #225.
Um sorry I don't know much about PR so I don't know how to make PR for issues.

**Comment by MattCSmith** [comment]
@fabrizvi No problem I will go ahead and close this issue. 

In your pull request you can add something like `closes #210` which upon the PR being merged it will close the issue. You can read more about it here: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by fabrizvi** [comment]
Thanks for letting me know Matt. 🤗
