### ISSUE TITLE
Fix Books layout

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#211]
Looks like there is an issue with the way cards are being displayed. Only one card on the right hand side should be displayed at any one time:
![image](https://user-images.githubusercontent.com/6190356/66208803-ebb8d380-e6ad-11e9-901d-ab1f63f3ba2a.png)

Also the footer should remain full width:
![image](https://user-images.githubusercontent.com/6190356/66208850-08eda200-e6ae-11e9-9d99-6068fd516f6b.png)

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by NitinNair89** [comment]
Happy to take this up. Please assign to me

**Comment by asprazz** [comment]
@NitinNair89 Are you still on it?

**Comment by NitinNair89** [comment]
Yes, I will do it today. Saturday morning just started here.

**Comment by asprazz** [comment]
I have done it 
Can I send PR ? Please  :+1:

**Comment by asprazz** [comment]
@MattCSmith Thank You for this opportunity... Looking forward to many contributions Please merge only if @NitinNair89 says yes.. :)

**Comment by NitinNair89** [comment]
> @MattCSmith Thank You for this opportunity... Looking forward to many contributions Please merge only if @NitinNair89 says yes.. :)

If you have already done the code changes, then it's fine. No point in re-doing stuffs :slightly_smiling_face:

**Comment by DiscoverSquishy** [comment]
@MattCSmith Can you confirm if this was fixed?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DiscoverSquishy** [comment]
(Sorry messed up and mistakenly closed this)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asprazz** [comment]
Please confirm if issue has been resolved or not ? If not i will do the required changes

**Comment by MattCSmith** [comment]
Closing as this appears to have been resolved
