### ISSUE TITLE
Activities page layout

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#212]
The cards could do with being spread across the page a little more removing the white space towards the right hand side

![image](https://user-images.githubusercontent.com/6190356/66208957-50742e00-e6ae-11e9-8d3d-3c30145cb21e.png)

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by KarlaChen** [comment]
Hi, @MattCSmith . Can I try to fix it?

**Comment by MattCSmith** [comment]
@KarlaChen perfect go for it 😃

**Comment by Shaikh-Ubaid** [comment]
Do you just want the cards to be positioned at the centre of the page with some increased size? I can do this

**Comment by Shaikh-Ubaid** [comment]
May be this should be closed now. I have fixed it and it has also been merged.
