### ISSUE TITLE
Activities Card Design

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#213]
These cards look a little plain, perhaps we could spice them up with some styling or images maybe

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by NitinNair89** [comment]
Do you have any design in mind?

**Comment by ramyamahi** [comment]
@MattCSmith   I would like to do this card design. Can I try this?

**Comment by ramyamahi** [comment]
#234
