### ISSUE TITLE
Elf name generator

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#214]
This page might benefit from some further styling to make it stand out a little more. 

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by AkshitAggarwal** [comment]
Hey, I'm basically starting out with HTML and CSS, I think I should work on this one. Please assign it to me.

**Comment by MattCSmith** [comment]
Hey @AkshitAggarwal 
How are you getting on with this task? Are you still interested in it?

**Comment by instinxt** [comment]
i guess i can continue here if this is still open

**Comment by MattCSmith** [comment]
@instinxt This can now be considered open, if you wish to tackle it?

**Comment by instinxt** [comment]
On it
