### ISSUE TITLE
Snowman name generator

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#215]
Perhaps we could rename the "Elf name generator" page to just "Name Generators" and create this snowman name generator:

![image](https://user-images.githubusercontent.com/6190356/66209324-02abf580-e6af-11e9-9e06-869c614f05db.png)

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by ann-dev** [comment]
Hi, I'm currently going through Zero To Mastery course, I would like to work on this project if possible :)

**Comment by MattCSmith** [comment]
Hey @ann-dev 
How is it going with this task? are you still working towards adding this new feature?

**Comment by ann-dev** [comment]
Yup, I'm working on it. Any style guides I should follow (should the final version be as close as possible to the image in first post or just have a ''holiday feel'' to it)?

**Comment by ann-dev** [comment]
Finished the generator page, I've also added a page linking to other generators. I'll make a pull request now. If there are any issues, please let me know.

**Comment by MattCSmith** [comment]
Looks great nice job 🙂

**Comment by kheyrasantos** [comment]
Regarding this: Perhaps we could rename the "Elf name generator" page to just "Name Generators" and create this snowman name generator... What exactly would you like done here? Just cloned the project. The html does not look anything like the mockup
