### ISSUE TITLE
Reindeer name generator

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#217]
Perhaps we could rename the "Elf name generator" page to just "Name Generators" and create this reindeer name generator:

![image](https://user-images.githubusercontent.com/6190356/66209411-34bd5780-e6af-11e9-8a62-e6fdd89de150.png)

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by jianweilee128** [comment]
I will work on this issue.

**Comment by instinxt** [comment]
Is this still open i would like to work on this :)

**Comment by MattCSmith** [comment]
@jianweilee128 How are you getting on with this task?
If you not keen on completing the task I'm sure @instinxt would be happy to go ahead an implement it

**Comment by jianweilee128** [comment]
I completed it already.
If you want you can help to fine tune it and modify the design.

**Comment by jianweilee128** [comment]
You could help to change the page name and the links to Name generator instead of elf name generator.

**Comment by MattCSmith** [comment]
> I completed it already.
> If you want you can help to fine tune it and modify the design.

@jianweilee128 Are you able to make a pull request, I dont see the page in the code base 🙂

**Comment by jianweilee128** [comment]
@MattCSmith i just checked and the reindeer name page i made is being put wrongly as the elf generator page.
Will send a pull request to rectify it.
