### ISSUE TITLE
Santa's Blog

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#218]
Create a blog page
with a similar layout to this:
![image](https://user-images.githubusercontent.com/6190356/66209643-b4e3bd00-e6af-11e9-8b08-bddd51b9b97c.png)

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by mmosehauer** [comment]
I'll take this one

**Comment by MattCSmith** [comment]
Closing as this appears to have been resolved
