### ISSUE TITLE
Standardise footer across all pages

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#219]
The index page has the footer inline with the design, lets apply this across all pages on the site

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by akmalist** [comment]
I can take and work on this.

**Comment by Ananthavijay** [comment]
can i work on this?

**Comment by ka-hn** [comment]
There is still inconsistensies on the footers trough the different pages (visual and logical). See examples below.

Can I continue on this and resolve it?

![index](https://user-images.githubusercontent.com/27919581/66274907-b2d25780-e883-11e9-9ef8-94a65ef342e8.PNG)
![Recipes](https://user-images.githubusercontent.com/27919581/66274908-b2d25780-e883-11e9-8311-9aab1f82cd1b.PNG)
![Activities](https://user-images.githubusercontent.com/27919581/66274909-b36aee00-e883-11e9-8cc6-2c2566ca51d9.PNG)

**Comment by MattCSmith** [comment]
Yes please @ka-hn, If you could bring them all inline with the design that would be fantastic

**Comment by ka-hn** [comment]
I will work on this. Issue claimed.

**Comment by MattCSmith** [comment]
How's this going @ka-hn ?

**Comment by ka-hn** [comment]
@MattCSmith Sorry I haven't pushed anything yet (single parent and working fulltime) but I will work on it and hope fullt push tonight.
