### ISSUE TITLE
The recipes title is copied from the movies page and all the section comments are from the same page. 

### ISSUE THREAD

**Issue by dppeykov** [zero-to-mastery/Santafied#25]
I'm working on fixing the title and the comments, as well as adding a new recipe to the list.

**Comment by anirudh-kac** [comment]
I have opened a pull request fixing the title of the same.

**Comment by dppeykov** [comment]
Ok, I will leave the title and just fix the comments.

**Comment by dppeykov** [comment]
The fixes are waiting to be merged. Closing the issue.
