### ISSUE TITLE
Jingle All the Way (in films) has no card image visible

### ISSUE THREAD

**Issue by Ray6464** [zero-to-mastery/Santafied#268]

**Comment by learnerjay** [comment]
![Screenshot (133)](https://user-images.githubusercontent.com/45159010/66308940-f2ea1680-e925-11e9-86fa-3115e1986051.png)
You can close the ticket, its working fine.

**Comment by Ray6464** [comment]
Checked again, still not working on my side.

Problem: Jingle All The Way card image not showing
stats: using Firefox, visiting the url of this image shows a server not found error. Perhaps use a picture from another host that is more widely available like this one: https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/Jingle_All_the_Way_poster.JPG/220px-Jingle_All_the_Way_poster.JPG

**Comment by henryvalbuena** [comment]
I believe this issue has been solved. I can see, using Firefox or Chrome, the new image proposed by @Ray6464 as the new source

**Please confirm.**

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/32443577/66439686-72e3af80-e9fe-11e9-9964-06cd7c04beac.png">

**Comment by Ray6464** [comment]
> I believe this issue has been solved. I can see, using Firefox or Chrome, the new image proposed by @Ray6464 as the new source
> 
> **Please confirm.**
> 
> <img alt="image" width="1110" src="https://user-images.githubusercontent.com/32443577/66439686-72e3af80-e9fe-11e9-9964-06cd7c04beac.png">

Confirmed, image is now visible on my side too.
