### ISSUE TITLE
Add 'Read More' links at Books section

### ISSUE THREAD

**Issue by stnbnvdz** [zero-to-mastery/Santafied#272]
Hi. I will work on this one. Thanks

**Comment by MattCSmith** [comment]
How is this going @stnbnvdz ?

**Comment by stnbnvdz** [comment]
Done doing it. Please see pull request
![Capturee](https://user-images.githubusercontent.com/21289962/66482286-7c4d3600-ea57-11e9-859c-4971797c792f.JPG)
