### ISSUE TITLE
Style card button on the facts page

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#278]
On the facts page, lets give the card a button rather than a text link.
Text should read: "Learn more" or "Find out more"
Matching the following design:
![image](https://user-images.githubusercontent.com/6190356/66304475-2b253100-e8f5-11e9-81a3-5c3ebadbd513.png)

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by dev-SB** [comment]
I would like to work on this issue.

**Comment by MattCSmith** [comment]
Awesome go ahead 👍
