### ISSUE TITLE
Style card button or film page

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#281]
On the films page, lets style the card a button inline with the design scheme.
Text should read: "Watch Now" or similar

Matching the following design:
![image](https://user-images.githubusercontent.com/6190356/66304475-2b253100-e8f5-11e9-81a3-5c3ebadbd513.png)

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by vincentalfred** [comment]
Hi
I would like to work on this issue

**Comment by kudoabhijeet** [comment]
Hey, I would like to contribute to this issue.
