### ISSUE TITLE
Songs page

### ISSUE THREAD

**Issue by ridbay** [zero-to-mastery/Santafied#307]
Embed audio player to each Christmas song, so that users can listen to the songs while reading the lyrics.

**Comment by ridbay** [comment]
> I'd like to take this one.

I have added the audio player options, check here [#309 Pull](https://github.com/zero-to-mastery/Santafied/pull/309)

**Comment by Pr0ftR3gret** [comment]
Gotcha, thanks!

**Comment by ridbay** [comment]
> Gotcha, thanks!

You're welcome.

you can still work on improving it.

**Comment by EricPuskas** [comment]
Hey guys! I'm not quite sure if it's just me but I can't seem to pull up all the songs. I click on the menu on the left and only a few of them work. "All I Want for Christmas Is You",  "Jingle Bells", these work, but "Run Rudolph Run" doesn't.  By clicking on it, nothing happens essentially.

**Comment by MattCSmith** [comment]
> Hey guys! I'm not quite sure if it's just me but I can't seem to pull up all the songs. I click on the menu on the left and only a few of them work. "All I Want for Christmas Is You", "Jingle Bells", these work, but "Run Rudolph Run" doesn't. By clicking on it, nothing happens essentially.

I seem to have this issue too. Since the original issue was solved, Im going to close this, will open a new issue to tackle that problem
