### ISSUE TITLE
Selecting movie from the list should scroll the document to top

### ISSUE THREAD

**Issue by ruchirV** [zero-to-mastery/Santafied#310]
The movies page has a big list now and selecting movies from the bottom of the screen should move the page up to start reading the description.

**Comment by ruchirV** [comment]
working on it..

**Comment by QuodIntrepidus** [comment]
Fixed the issue of scrolling to top.

**Comment by akmalist** [comment]
Can someone also fix the last button for movie? 
"The Christmas Chronicles"
