### ISSUE TITLE
[CREATE] Games Page

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#32]
Create the basic page skeleton for the games page, inline with the design.
### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by mayankwadhwani** [comment]
Can you please ellaborate, i want to work on this.

**Comment by MattCSmith** [comment]
You just need to create the basic page layout to match the design as the page does not currently exist. 
Dont worry so much about making sure all the content is there, that can be done in future PRs.

**Comment by sianlouisa** [comment]
Hi, happy to work on this if @mayankwadhwani has not claimed? :smile:
