### ISSUE TITLE
[CREATE] Activities Page

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#33]
Create the basic page skeleton for the Activities page, inline with the design.

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by Edmund1645** [comment]
I will be working on this.
Also, I cannot seem to drag the card referencing this issue on the task board to `in progress`

**Comment by MattCSmith** [comment]
I have moved it for you. I will look into why that is
