### ISSUE TITLE
[BUG] Films.html - Show a default film

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#34]
It would be nice, if on page load this showed the first film, rather than white space. Much like the Recipes page.
![image](https://user-images.githubusercontent.com/6190356/65949781-bf465280-e434-11e9-9b8f-15a88ae5319f.png)

**Comment by sanjaymahto** [comment]
hey! can I take this issue?

**Comment by MattCSmith** [comment]
Sure move it over to the in progress section on the taskboard here:
https://github.com/zero-to-mastery/Santafied/projects/1

**Comment by MattCSmith** [comment]
Actually @sanjaymahto this has already been solved. The books page has the same problem you can fix thought?
