### ISSUE TITLE
mouse-trail-snowball causing overflow x-axis of body element

### ISSUE THREAD

**Issue by ka-hn** [zero-to-mastery/Santafied#340]
When moving the mouse to the right outside of the page the mouse-trail-snowball is causing page to overflow on x-axis.

![Capture](https://user-images.githubusercontent.com/27919581/66515604-b104d000-eadf-11e9-9069-09ce11c2d82c.PNG)

**Comment by itsaiub** [comment]
I will fix this issue

**Comment by MattCSmith** [comment]
How is this going @itsaiub ?

**Comment by ka-hn** [comment]
@itsaiub Are you working on it? Otherwise I will fix it, it's kinda simple.
