### ISSUE TITLE
fix the display of the book page

### ISSUE THREAD

**Issue by shafer949** [zero-to-mastery/Santafied#353]
1. Only show the book Twas The Night Before Christmas when the tab is selected.
2. Remove the <<<<<<< HEAD related code.
3. Only show the Polar Express when tab is selected.

**Comment by shafer949** [comment]
I am working on this issue.

**Comment by MattCSmith** [comment]
@shafer949 How is is issue going. Appears the PR has a conflict on it that needs resolving

**Comment by shafer949** [comment]
I will take a look at the PR and fix the conflict.

**Comment by shafer949** [comment]
@MattCSmith it looks like this was fixed already with a different PR now. I will close this one.
