### ISSUE TITLE
[Fix] Homepage nav on mobile

### ISSUE THREAD

**Issue by sebulbausb** [zero-to-mastery/Santafied#36]
Currently, the main nav doesn't work on the homepage.

**Comment by MattCSmith** [comment]
### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK ITS STILL AVAILABLE & MOVE IT TO THE `IN PROGRESS` SECTION [here](https://github.com/zero-to-mastery/Santafied/projects/1)**

**Comment by sebulbausb** [comment]
I can fix it, but have no idea how to move it to "in progress"

**Comment by MattCSmith** [comment]
Yeah apparently the task boards arent flexible enough permission wise for what we need. Im going to close the permission board and just use issues/comments.

**Comment by MattCSmith** [comment]
Closing as resolved in #43
