### ISSUE TITLE
Reuse code for header and footer part in all the pages

### ISSUE THREAD

**Issue by ruchirV** [zero-to-mastery/Santafied#377]
There is so much repetitive code in all the html pages for the header and the footer parts. I am sure there must be some way to reuse the code by writing separate header and footer html pages and including that in the main pages.. can someone try that?

**Comment by MattCSmith** [comment]
@itsaiub Im sure you have noticed already, but this should already be present on the header

**Comment by MattCSmith** [comment]
@itsaiub Are you still working on this?

**Comment by AbdussamadYisau** [comment]
Would like to take this up if it's still available
