### ISSUE TITLE
[CONTENT] - Add page content - Ongoing task, everyone can do this

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#42]
### **This task is on going, we can never have enough content 😄** 

Several pages are in need of some content cards. You can add as many as you like for any of the following: 

- Recipes
- Songs
- Films
- Books

Once the following pages have been created they will also likely need content too:
- Facts
- Games
- Activities

**Comment by shivamkainth** [comment]
I am going to work on this.

**Comment by ChristinaJackson** [comment]
There are no party costumes! I'll work on adding some

**Comment by vipinkumar96** [comment]
I will be adding more facts to the repo.

**Comment by kohli6010** [comment]
I would like to add books regarding christmas

**Comment by danielharvilik** [comment]
I would like to take movies

**Comment by jflopezr11** [comment]
I would like to add more recipes! 👍

**Comment by stnbnvdz** [comment]
I would like to participate and add more to this especially books.

**Comment by jflopezr11** [comment]
I would like to fix up the recipes page to be a bit more mobile responsive. would anyone like to help me with that? please.

**Comment by Valentinezhen** [comment]
#424 Add Jack Frost to films page

**Comment by grieff** [comment]
I've added a new film #443 
I may add more films and recipes in the next days :)

**Comment by zullo91** [comment]
Could we add a new page or split the existing Game page, into two different parts, a Real and Digital Video Games ?

**Comment by obulaworld** [comment]
I will like to add more Films and Songs

**Comment by obulaworld** [comment]
> Could we add a new page or split the existing Game page, into two different parts, a Real and Digital Video Games ?

I would like to split this

**Comment by Aravindh-SNR** [comment]
Hi, I've added 3 more activities in the activities page. PR #528.
Cheers :)

**Comment by nnh242** [comment]
I will add more content for recipes.
