### ISSUE TITLE
[UPDATE]  Index Carousel

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#51]
We seem to have two carousels for the index page, we only need one, ideally it should match the [design](https://raw.githubusercontent.com/zero-to-mastery/Santafied/master/design/general-layout.png) as closely as possible 😄 

### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by marekgebka** [comment]
I'll take care of it.

**Comment by bolajiscott** [comment]
i can work on this

**Comment by MattCSmith** [comment]
Closing as addressed in #62
