### ISSUE TITLE
[UPDATE] Gifts Page

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Santafied#54]
I think it would be awesome if changed up the gifts page slightly. Lets have:

-  The "categories" as a nicely sized `<h2>`'s
- `<h3> or <p>` Subtile
- Then use the [Card Varient 2](https://github.com/zero-to-mastery/Santafied/blob/master/design/card-designs.png) for the designs to list some products, for example:

#### Plush Toys are always the cutest gifts. Especially kids would love them for sure.
<Card Plush 1>       <Card Plush 2>     <Card Plush 3>

---
> ### **IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING**

**Comment by ikrydev** [comment]
Can I Assign for this ?

**Comment by bolajiscott** [comment]
am intrested on working on this
