### ISSUE TITLE
add lazy load 

### ISSUE THREAD

**Issue by jlapitan** [zero-to-mastery/Santafied#89]
Add lazy load functionality for the images.

**Comment by TehPsychedelic** [comment]
Improvements:
 - Verify if the browser supports lazy loading natively (Chrome 75/76+), then just use the "loading" property instead of an observer with a viewpoint.
 - Use tiny thumbnails or a "cool" placeholder for the images before they load.

**Comment by takaras** [comment]
Lazy loading should be used only for images below the fold.
The above the fold images are critical assets that must be loaded as soon as possible.
[More on this topic](https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video#mind_the_fold)

**Comment by MattCSmith** [comment]
Closing as I think this has been resolved, feel free to reopen if not
